mx:
  value: 30.0
  min: 0.0
  max: 100.0
my:
  value: 30.0
  min: 0.0
  max: 100.0
mz:
  value: 30.0
  min: 0.0
  max: 100.0
bx:
  value: 20.0
  min: 0.0
  max: 100.0
by:
  value: 20.0
  min: 0.0
  max: 100.0
bz:  
  value: 20.0
  min: 0.0
  max: 100.0
